/* tslint:disable */
/* eslint-disable */

// ######################################## THIS FILE WAS GENERATED BY MONGOOSE-TSGEN ######################################## //

// NOTE: ANY CHANGES MADE WILL BE OVERWRITTEN ON SUBSEQUENT EXECUTIONS OF MONGOOSE-TSGEN.

import mongoose from "mongoose";

/**
 * Lean version of WebsiteDataHomeSectionStatDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataHomeSectionDocument.toObject()`.
 * ```
 * const websitedatahomesectionObject = websitedatahomesection.toObject();
 * ```
 */
export type WebsiteDataHomeSectionStat = {
  title?: string;
  value?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of WebsiteDataHomeSectionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataDocument.toObject()`.
 * ```
 * const websitedataObject = websitedata.toObject();
 * ```
 */
export type WebsiteDataHomeSection = {
  title?: string;
  founded?: string;
  subtitle?: string;
  _id: mongoose.Types.ObjectId;
  stats: WebsiteDataHomeSectionStat[];
};

/**
 * Lean version of WebsiteDataNavigationBarItemDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataNavigationBarDocument.toObject()`.
 * ```
 * const websitedatanavigationbarObject = websitedatanavigationbar.toObject();
 * ```
 */
export type WebsiteDataNavigationBarItem = {
  label: string;
  link?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of WebsiteDataNavigationBarDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataDocument.toObject()`.
 * ```
 * const websitedataObject = websitedata.toObject();
 * ```
 */
export type WebsiteDataNavigationBar = {
  changeLanguageLabel?: string;
  _id: mongoose.Types.ObjectId;
  items: WebsiteDataNavigationBarItem[];
};

/**
 * Lean version of WebsiteDataAboutSectionCardDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataAboutSectionDocument.toObject()`.
 * ```
 * const websitedataaboutsectionObject = websitedataaboutsection.toObject();
 * ```
 */
export type WebsiteDataAboutSectionCard = {
  title?: string;
  image?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of WebsiteDataAboutSectionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataDocument.toObject()`.
 * ```
 * const websitedataObject = websitedata.toObject();
 * ```
 */
export type WebsiteDataAboutSection = {
  title?: string;
  _id: mongoose.Types.ObjectId;
  cards: WebsiteDataAboutSectionCard[];
};

/**
 * Lean version of WebsiteDataEventsSectionEventButtonDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataEventsSectionEventDocument.toObject()`.
 * ```
 * const websitedataeventssectioneventObject = websitedataeventssectionevent.toObject();
 * ```
 */
export type WebsiteDataEventsSectionEventButton = {
  label?: string;
  link?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of WebsiteDataEventsSectionEventDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataEventsSectionDocument.toObject()`.
 * ```
 * const websitedataeventssectionObject = websitedataeventssection.toObject();
 * ```
 */
export type WebsiteDataEventsSectionEvent = {
  title: string;
  image: string;
  startDate: Date;
  endDate?: Date;
  _id: mongoose.Types.ObjectId;
  button?: WebsiteDataEventsSectionEventButton;
};

/**
 * Lean version of WebsiteDataEventsSectionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataDocument.toObject()`.
 * ```
 * const websitedataObject = websitedata.toObject();
 * ```
 */
export type WebsiteDataEventsSection = {
  title?: string;
  _id: mongoose.Types.ObjectId;
  events: WebsiteDataEventsSectionEvent[];
};

/**
 * Lean version of WebsiteDataProgramsSectionProgramButtonDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataProgramsSectionProgramDocument.toObject()`.
 * ```
 * const websitedataprogramssectionprogramObject = websitedataprogramssectionprogram.toObject();
 * ```
 */
export type WebsiteDataProgramsSectionProgramButton = {
  label?: string;
  link?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of WebsiteDataProgramsSectionProgramDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataProgramsSectionDocument.toObject()`.
 * ```
 * const websitedataprogramssectionObject = websitedataprogramssection.toObject();
 * ```
 */
export type WebsiteDataProgramsSectionProgram = {
  title?: string;
  description?: string;
  grade?: string;
  _id: mongoose.Types.ObjectId;
  button?: WebsiteDataProgramsSectionProgramButton;
};

/**
 * Lean version of WebsiteDataProgramsSectionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataDocument.toObject()`.
 * ```
 * const websitedataObject = websitedata.toObject();
 * ```
 */
export type WebsiteDataProgramsSection = {
  title?: string;
  _id: mongoose.Types.ObjectId;
  programs: WebsiteDataProgramsSectionProgram[];
};

/**
 * Lean version of WebsiteDataSubjectsSectionSubjectDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataSubjectsSectionDocument.toObject()`.
 * ```
 * const websitedatasubjectssectionObject = websitedatasubjectssection.toObject();
 * ```
 */
export type WebsiteDataSubjectsSectionSubject = {
  title?: string;
  description?: string;
  image?: string;
  grade?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of WebsiteDataSubjectsSectionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataDocument.toObject()`.
 * ```
 * const websitedataObject = websitedata.toObject();
 * ```
 */
export type WebsiteDataSubjectsSection = {
  title?: string;
  viewMoreLabel?: string;
  _id: mongoose.Types.ObjectId;
  subjects: WebsiteDataSubjectsSectionSubject[];
};

/**
 * Lean version of WebsiteDataScheduleSectionActiveDateDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataScheduleSectionDocument.toObject()`.
 * ```
 * const websitedataschedulesectionObject = websitedataschedulesection.toObject();
 * ```
 */
export type WebsiteDataScheduleSectionActiveDate = {
  date: Date;
  time?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of WebsiteDataScheduleSectionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataDocument.toObject()`.
 * ```
 * const websitedataObject = websitedata.toObject();
 * ```
 */
export type WebsiteDataScheduleSection = {
  title?: string;
  _id: mongoose.Types.ObjectId;
  activeDates: WebsiteDataScheduleSectionActiveDate[];
};

/**
 * Lean version of WebsiteDataQuestionsSectionQuestionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataQuestionsSectionDocument.toObject()`.
 * ```
 * const websitedataquestionssectionObject = websitedataquestionssection.toObject();
 * ```
 */
export type WebsiteDataQuestionsSectionQuestion = {
  question?: string;
  answer?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of WebsiteDataQuestionsSectionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataDocument.toObject()`.
 * ```
 * const websitedataObject = websitedata.toObject();
 * ```
 */
export type WebsiteDataQuestionsSection = {
  title?: string;
  _id: mongoose.Types.ObjectId;
  questions: WebsiteDataQuestionsSectionQuestion[];
};

/**
 * Lean version of WebsiteDataTeamSectionMemberDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataTeamSectionDocument.toObject()`.
 * ```
 * const websitedatateamsectionObject = websitedatateamsection.toObject();
 * ```
 */
export type WebsiteDataTeamSectionMember = {
  firstName: string;
  lastName: string;
  image?: string;
  role?: string;
  description?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of WebsiteDataTeamSectionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataDocument.toObject()`.
 * ```
 * const websitedataObject = websitedata.toObject();
 * ```
 */
export type WebsiteDataTeamSection = {
  title?: string;
  _id: mongoose.Types.ObjectId;
  members: WebsiteDataTeamSectionMember[];
};

/**
 * Lean version of WebsiteDataTestimonialsSectionTestimonialDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataTestimonialsSectionDocument.toObject()`.
 * ```
 * const websitedatatestimonialssectionObject = websitedatatestimonialssection.toObject();
 * ```
 */
export type WebsiteDataTestimonialsSectionTestimonial = {
  attestant: string;
  title: string;
  description: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of WebsiteDataTestimonialsSectionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataDocument.toObject()`.
 * ```
 * const websitedataObject = websitedata.toObject();
 * ```
 */
export type WebsiteDataTestimonialsSection = {
  title?: string;
  _id: mongoose.Types.ObjectId;
  testimonials: WebsiteDataTestimonialsSectionTestimonial[];
};

/**
 * Lean version of WebsiteDataContactSectionContactInfoDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataContactSectionDocument.toObject()`.
 * ```
 * const websitedatacontactsectionObject = websitedatacontactsection.toObject();
 * ```
 */
export type WebsiteDataContactSectionContactInfo = {
  email?: string;
  phone?: string;
  wechat?: string;
  instagram?: string;
  youtube?: string;
  facebook?: string;
  twitter?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of WebsiteDataContactSectionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataDocument.toObject()`.
 * ```
 * const websitedataObject = websitedata.toObject();
 * ```
 */
export type WebsiteDataContactSection = {
  title?: string;
  _id: mongoose.Types.ObjectId;
  contactInfo: WebsiteDataContactSectionContactInfo;
};

/**
 * Lean version of WebsiteDataDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `WebsiteDataDocument.toObject()`. To avoid conflicts with model names, use the type alias `WebsiteDataObject`.
 * ```
 * const websitedataObject = websitedata.toObject();
 * ```
 */
export type WebsiteData = {
  language: string;
  terms: string;
  _id: mongoose.Types.ObjectId;
  homeSection: WebsiteDataHomeSection;
  navigationBar: WebsiteDataNavigationBar;
  aboutSection: WebsiteDataAboutSection;
  eventsSection: WebsiteDataEventsSection;
  programsSection: WebsiteDataProgramsSection;
  subjectsSection: WebsiteDataSubjectsSection;
  scheduleSection: WebsiteDataScheduleSection;
  questionsSection: WebsiteDataQuestionsSection;
  teamSection: WebsiteDataTeamSection;
  testimonialsSection: WebsiteDataTestimonialsSection;
  contactSection: WebsiteDataContactSection;
};

/**
 * Lean version of WebsiteDataDocument (type alias of `WebsiteData`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { WebsiteData } from "../models"
 * import { WebsiteDataObject } from "../interfaces/mongoose.gen.ts"
 *
 * const websitedataObject: WebsiteDataObject = websitedata.toObject();
 * ```
 */
export type WebsiteDataObject = WebsiteData;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type WebsiteDataQuery = mongoose.Query<
  any,
  WebsiteDataDocument,
  WebsiteDataQueries
> &
  WebsiteDataQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `WebsiteDataSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type WebsiteDataQueries = {};

export type WebsiteDataMethods = {};

export type WebsiteDataStatics = {};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteData = mongoose.model<WebsiteDataDocument, WebsiteDataModel>("WebsiteData", WebsiteDataSchema);
 * ```
 */
export type WebsiteDataModel = mongoose.Model<
  WebsiteDataDocument,
  WebsiteDataQueries,
  WebsiteDataMethods
> &
  WebsiteDataStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new WebsiteData schema instances:
 * ```
 * const WebsiteDataSchema: WebsiteDataSchema = new mongoose.Schema({ ... })
 * ```
 */
export type WebsiteDataSchema = mongoose.Schema<
  WebsiteDataDocument,
  WebsiteDataModel,
  WebsiteDataMethods,
  WebsiteDataQueries
>;

/**
 * Mongoose Subdocument type
 *
 * Type of `WebsiteDataHomeSectionDocument["stats"]` element.
 */
export type WebsiteDataHomeSectionStatDocument = mongoose.Types.Subdocument & {
  title?: string;
  value?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteData = mongoose.model<WebsiteDataDocument, WebsiteDataModel>("WebsiteData", WebsiteDataSchema);
 * ```
 */
export type WebsiteDataHomeSectionDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    title?: string;
    founded?: string;
    subtitle?: string;
    _id: mongoose.Types.ObjectId;
    stats: mongoose.Types.DocumentArray<WebsiteDataHomeSectionStatDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `WebsiteDataNavigationBarDocument["items"]` element.
 */
export type WebsiteDataNavigationBarItemDocument =
  mongoose.Types.Subdocument & {
    label: string;
    link?: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteData = mongoose.model<WebsiteDataDocument, WebsiteDataModel>("WebsiteData", WebsiteDataSchema);
 * ```
 */
export type WebsiteDataNavigationBarDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    changeLanguageLabel?: string;
    _id: mongoose.Types.ObjectId;
    items: mongoose.Types.DocumentArray<WebsiteDataNavigationBarItemDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `WebsiteDataAboutSectionDocument["cards"]` element.
 */
export type WebsiteDataAboutSectionCardDocument = mongoose.Types.Subdocument & {
  title?: string;
  image?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteData = mongoose.model<WebsiteDataDocument, WebsiteDataModel>("WebsiteData", WebsiteDataSchema);
 * ```
 */
export type WebsiteDataAboutSectionDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    title?: string;
    _id: mongoose.Types.ObjectId;
    cards: mongoose.Types.DocumentArray<WebsiteDataAboutSectionCardDocument>;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteDataEventsSectionEvent = mongoose.model<WebsiteDataEventsSectionEventDocument, WebsiteDataEventsSectionEventModel>("WebsiteDataEventsSectionEvent", WebsiteDataEventsSectionEventSchema);
 * ```
 */
export type WebsiteDataEventsSectionEventButtonDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    label?: string;
    link?: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `WebsiteDataEventsSectionDocument["events"]` element.
 */
export type WebsiteDataEventsSectionEventDocument =
  mongoose.Types.Subdocument & {
    title: string;
    image: string;
    startDate: Date;
    endDate?: Date;
    _id: mongoose.Types.ObjectId;
    button?: WebsiteDataEventsSectionEventButtonDocument;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteData = mongoose.model<WebsiteDataDocument, WebsiteDataModel>("WebsiteData", WebsiteDataSchema);
 * ```
 */
export type WebsiteDataEventsSectionDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    title?: string;
    _id: mongoose.Types.ObjectId;
    events: mongoose.Types.DocumentArray<WebsiteDataEventsSectionEventDocument>;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteDataProgramsSectionProgram = mongoose.model<WebsiteDataProgramsSectionProgramDocument, WebsiteDataProgramsSectionProgramModel>("WebsiteDataProgramsSectionProgram", WebsiteDataProgramsSectionProgramSchema);
 * ```
 */
export type WebsiteDataProgramsSectionProgramButtonDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    label?: string;
    link?: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `WebsiteDataProgramsSectionDocument["programs"]` element.
 */
export type WebsiteDataProgramsSectionProgramDocument =
  mongoose.Types.Subdocument & {
    title?: string;
    description?: string;
    grade?: string;
    _id: mongoose.Types.ObjectId;
    button?: WebsiteDataProgramsSectionProgramButtonDocument;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteData = mongoose.model<WebsiteDataDocument, WebsiteDataModel>("WebsiteData", WebsiteDataSchema);
 * ```
 */
export type WebsiteDataProgramsSectionDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    title?: string;
    _id: mongoose.Types.ObjectId;
    programs: mongoose.Types.DocumentArray<WebsiteDataProgramsSectionProgramDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `WebsiteDataSubjectsSectionDocument["subjects"]` element.
 */
export type WebsiteDataSubjectsSectionSubjectDocument =
  mongoose.Types.Subdocument & {
    title?: string;
    description?: string;
    image?: string;
    grade?: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteData = mongoose.model<WebsiteDataDocument, WebsiteDataModel>("WebsiteData", WebsiteDataSchema);
 * ```
 */
export type WebsiteDataSubjectsSectionDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    title?: string;
    viewMoreLabel?: string;
    _id: mongoose.Types.ObjectId;
    subjects: mongoose.Types.DocumentArray<WebsiteDataSubjectsSectionSubjectDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `WebsiteDataScheduleSectionDocument["activeDates"]` element.
 */
export type WebsiteDataScheduleSectionActiveDateDocument =
  mongoose.Types.Subdocument & {
    date: Date;
    time?: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteData = mongoose.model<WebsiteDataDocument, WebsiteDataModel>("WebsiteData", WebsiteDataSchema);
 * ```
 */
export type WebsiteDataScheduleSectionDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    title?: string;
    _id: mongoose.Types.ObjectId;
    activeDates: mongoose.Types.DocumentArray<WebsiteDataScheduleSectionActiveDateDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `WebsiteDataQuestionsSectionDocument["questions"]` element.
 */
export type WebsiteDataQuestionsSectionQuestionDocument =
  mongoose.Types.Subdocument & {
    question?: string;
    answer?: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteData = mongoose.model<WebsiteDataDocument, WebsiteDataModel>("WebsiteData", WebsiteDataSchema);
 * ```
 */
export type WebsiteDataQuestionsSectionDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    title?: string;
    _id: mongoose.Types.ObjectId;
    questions: mongoose.Types.DocumentArray<WebsiteDataQuestionsSectionQuestionDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `WebsiteDataTeamSectionDocument["members"]` element.
 */
export type WebsiteDataTeamSectionMemberDocument =
  mongoose.Types.Subdocument & {
    firstName: string;
    lastName: string;
    image?: string;
    role?: string;
    description?: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteData = mongoose.model<WebsiteDataDocument, WebsiteDataModel>("WebsiteData", WebsiteDataSchema);
 * ```
 */
export type WebsiteDataTeamSectionDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    title?: string;
    _id: mongoose.Types.ObjectId;
    members: mongoose.Types.DocumentArray<WebsiteDataTeamSectionMemberDocument>;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `WebsiteDataTestimonialsSectionDocument["testimonials"]` element.
 */
export type WebsiteDataTestimonialsSectionTestimonialDocument =
  mongoose.Types.Subdocument & {
    attestant: string;
    title: string;
    description: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteData = mongoose.model<WebsiteDataDocument, WebsiteDataModel>("WebsiteData", WebsiteDataSchema);
 * ```
 */
export type WebsiteDataTestimonialsSectionDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    title?: string;
    _id: mongoose.Types.ObjectId;
    testimonials: mongoose.Types.DocumentArray<WebsiteDataTestimonialsSectionTestimonialDocument>;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteDataContactSection = mongoose.model<WebsiteDataContactSectionDocument, WebsiteDataContactSectionModel>("WebsiteDataContactSection", WebsiteDataContactSectionSchema);
 * ```
 */
export type WebsiteDataContactSectionContactInfoDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    email?: string;
    phone?: string;
    wechat?: string;
    instagram?: string;
    youtube?: string;
    facebook?: string;
    twitter?: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteData = mongoose.model<WebsiteDataDocument, WebsiteDataModel>("WebsiteData", WebsiteDataSchema);
 * ```
 */
export type WebsiteDataContactSectionDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    title?: string;
    _id: mongoose.Types.ObjectId;
    contactInfo: WebsiteDataContactSectionContactInfoDocument;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const WebsiteData = mongoose.model<WebsiteDataDocument, WebsiteDataModel>("WebsiteData", WebsiteDataSchema);
 * ```
 */
export type WebsiteDataDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  WebsiteDataQueries
> &
  WebsiteDataMethods & {
    language: string;
    terms: string;
    _id: mongoose.Types.ObjectId;
    homeSection: WebsiteDataHomeSectionDocument;
    navigationBar: WebsiteDataNavigationBarDocument;
    aboutSection: WebsiteDataAboutSectionDocument;
    eventsSection: WebsiteDataEventsSectionDocument;
    programsSection: WebsiteDataProgramsSectionDocument;
    subjectsSection: WebsiteDataSubjectsSectionDocument;
    scheduleSection: WebsiteDataScheduleSectionDocument;
    questionsSection: WebsiteDataQuestionsSectionDocument;
    teamSection: WebsiteDataTeamSectionDocument;
    testimonialsSection: WebsiteDataTestimonialsSectionDocument;
    contactSection: WebsiteDataContactSectionDocument;
  };

/**
 * Check if a property on a document is populated:
 * ```
 * import { IsPopulated } from "../interfaces/mongoose.gen.ts"
 *
 * if (IsPopulated<UserDocument["bestFriend"]>) { ... }
 * ```
 */
export function IsPopulated<T>(doc: T | mongoose.Types.ObjectId): doc is T {
  return doc instanceof mongoose.Document;
}

/**
 * Helper type used by `PopulatedDocument`. Returns the parent property of a string
 * representing a nested property (i.e. `friend.user` -> `friend`)
 */
type ParentProperty<T> = T extends `${infer P}.${string}` ? P : never;

/**
 * Helper type used by `PopulatedDocument`. Returns the child property of a string
 * representing a nested property (i.e. `friend.user` -> `user`).
 */
type ChildProperty<T> = T extends `${string}.${infer C}` ? C : never;

/**
 * Helper type used by `PopulatedDocument`. Removes the `ObjectId` from the general union type generated
 * for ref documents (i.e. `mongoose.Types.ObjectId | UserDocument` -> `UserDocument`)
 */
type PopulatedProperty<Root, T extends keyof Root> = Omit<Root, T> & {
  [ref in T]: Root[T] extends mongoose.Types.Array<infer U>
    ? mongoose.Types.Array<Exclude<U, mongoose.Types.ObjectId>>
    : Exclude<Root[T], mongoose.Types.ObjectId>;
};

/**
 * Populate properties on a document type:
 * ```
 * import { PopulatedDocument } from "../interfaces/mongoose.gen.ts"
 *
 * function example(user: PopulatedDocument<UserDocument, "bestFriend">) {
 *   console.log(user.bestFriend._id) // typescript knows this is populated
 * }
 * ```
 */
export type PopulatedDocument<DocType, T> = T extends keyof DocType
  ? PopulatedProperty<DocType, T>
  : ParentProperty<T> extends keyof DocType
  ? Omit<DocType, ParentProperty<T>> & {
      [ref in ParentProperty<T>]: DocType[ParentProperty<T>] extends mongoose.Types.Array<
        infer U
      >
        ? mongoose.Types.Array<
            ChildProperty<T> extends keyof U
              ? PopulatedProperty<U, ChildProperty<T>>
              : PopulatedDocument<U, ChildProperty<T>>
          >
        : ChildProperty<T> extends keyof DocType[ParentProperty<T>]
        ? PopulatedProperty<DocType[ParentProperty<T>], ChildProperty<T>>
        : PopulatedDocument<DocType[ParentProperty<T>], ChildProperty<T>>;
    }
  : DocType;

/**
 * Helper types used by the populate overloads
 */
type Unarray<T> = T extends Array<infer U> ? U : T;
type Modify<T, R> = Omit<T, keyof R> & R;

/**
 * Augment mongoose with Query.populate overloads
 */
declare module "mongoose" {
  interface Query<ResultType, DocType extends Document, THelpers = {}> {
    populate<T extends string>(
      path: T,
      select?: string | any,
      model?: string | Model<any, THelpers>,
      match?: any
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers;

    populate<T extends string>(
      options: Modify<PopulateOptions, { path: T }> | Array<PopulateOptions>
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers;
  }
}
